
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author myaduncan
 */
public class CreateAccount extends javax.swing.JFrame {

    /**
     * Creates new form CreateAccount
     */
    public CreateAccount() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        REgisterAccontPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CloseRegisterAccountForm = new javax.swing.JLabel();
        MinimizeRegisterAccountForm = new javax.swing.JLabel();
        RegisterAccountBackground = new javax.swing.JPanel();
        Email = new javax.swing.JLabel();
        LastName = new javax.swing.JLabel();
        GoBackToLoginArea = new javax.swing.JButton();
        RegisterNewUser = new javax.swing.JButton();
        Username = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        EnterPassword = new javax.swing.JPasswordField();
        RetypePassword = new javax.swing.JLabel();
        EnterPasswordAgain = new javax.swing.JPasswordField();
        FirstNameEntry = new javax.swing.JTextField();
        LastNameEntry = new javax.swing.JTextField();
        UsernameEntry = new javax.swing.JTextField();
        FirstName = new javax.swing.JLabel();
        EmailEntry = new javax.swing.JTextField();
        BirthDate = new javax.swing.JLabel();
        datePicker1 = new com.github.lgooddatepicker.components.DatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        REgisterAccontPanel.setBackground(new java.awt.Color(207, 0, 14));

        jLabel1.setFont(new java.awt.Font("DIN Condensed", 0, 18)); // NOI18N
        jLabel1.setText("Register Account");

        CloseRegisterAccountForm.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        CloseRegisterAccountForm.setText("x");
        CloseRegisterAccountForm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseRegisterAccountForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseRegisterAccountFormMouseClicked(evt);
            }
        });

        MinimizeRegisterAccountForm.setText("-");
        MinimizeRegisterAccountForm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MinimizeRegisterAccountForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeRegisterAccountFormMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout REgisterAccontPanelLayout = new javax.swing.GroupLayout(REgisterAccontPanel);
        REgisterAccontPanel.setLayout(REgisterAccontPanelLayout);
        REgisterAccontPanelLayout.setHorizontalGroup(
            REgisterAccontPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, REgisterAccontPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(117, 117, 117)
                .addComponent(MinimizeRegisterAccountForm)
                .addGap(18, 18, 18)
                .addComponent(CloseRegisterAccountForm)
                .addGap(17, 17, 17))
        );
        REgisterAccontPanelLayout.setVerticalGroup(
            REgisterAccontPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(REgisterAccontPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(REgisterAccontPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CloseRegisterAccountForm)
                    .addComponent(MinimizeRegisterAccountForm))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, REgisterAccontPanelLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        RegisterAccountBackground.setBackground(new java.awt.Color(0, 169, 207));

        Email.setFont(new java.awt.Font("DIN Condensed", 0, 18)); // NOI18N
        Email.setForeground(new java.awt.Color(255, 255, 255));
        Email.setText("Email");

        LastName.setFont(new java.awt.Font("DIN Condensed", 0, 18)); // NOI18N
        LastName.setForeground(new java.awt.Color(255, 255, 255));
        LastName.setText("Last Name");

        GoBackToLoginArea.setText("Login");
        GoBackToLoginArea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GoBackToLoginArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBackToLoginAreaActionPerformed(evt);
            }
        });

        RegisterNewUser.setText("Create Account");
        RegisterNewUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegisterNewUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterNewUserMouseClicked(evt);
            }
        });

        Username.setFont(new java.awt.Font("DIN Condensed", 0, 18)); // NOI18N
        Username.setForeground(new java.awt.Color(255, 255, 255));
        Username.setText("Username");

        Password.setFont(new java.awt.Font("DIN Condensed", 0, 18)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setText("Password");

        RetypePassword.setFont(new java.awt.Font("DIN Condensed", 0, 18)); // NOI18N
        RetypePassword.setForeground(new java.awt.Color(255, 255, 255));
        RetypePassword.setText("Retype Password");

        FirstName.setFont(new java.awt.Font("DIN Condensed", 0, 18)); // NOI18N
        FirstName.setForeground(new java.awt.Color(255, 255, 255));
        FirstName.setText("First Name");

        BirthDate.setFont(new java.awt.Font("DIN Condensed", 0, 18)); // NOI18N
        BirthDate.setForeground(new java.awt.Color(255, 255, 255));
        BirthDate.setText("Birth Date");

        datePicker1.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout RegisterAccountBackgroundLayout = new javax.swing.GroupLayout(RegisterAccountBackground);
        RegisterAccountBackground.setLayout(RegisterAccountBackgroundLayout);
        RegisterAccountBackgroundLayout.setHorizontalGroup(
            RegisterAccountBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterAccountBackgroundLayout.createSequentialGroup()
                .addGroup(RegisterAccountBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegisterAccountBackgroundLayout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addGroup(RegisterAccountBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(GoBackToLoginArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RegisterNewUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(RegisterAccountBackgroundLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(RegisterAccountBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(RegisterAccountBackgroundLayout.createSequentialGroup()
                                .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EnterPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(RegisterAccountBackgroundLayout.createSequentialGroup()
                                .addGroup(RegisterAccountBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LastName)
                                    .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(RegisterAccountBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(UsernameEntry)
                                    .addComponent(LastNameEntry)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterAccountBackgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(RegisterAccountBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterAccountBackgroundLayout.createSequentialGroup()
                                .addGroup(RegisterAccountBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(RetypePassword)
                                    .addComponent(BirthDate)
                                    .addComponent(Email))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(RegisterAccountBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(EnterPasswordAgain, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                                    .addComponent(EmailEntry)
                                    .addComponent(datePicker1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterAccountBackgroundLayout.createSequentialGroup()
                                .addComponent(FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(FirstNameEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        RegisterAccountBackgroundLayout.setVerticalGroup(
            RegisterAccountBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterAccountBackgroundLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(RegisterAccountBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstName)
                    .addComponent(FirstNameEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegisterAccountBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(RegisterAccountBackgroundLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(LastNameEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(RegisterAccountBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Username)
                    .addGroup(RegisterAccountBackgroundLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(UsernameEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(RegisterAccountBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Password)
                    .addGroup(RegisterAccountBackgroundLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(EnterPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(RegisterAccountBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnterPasswordAgain, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RetypePassword))
                .addGap(18, 18, 18)
                .addGroup(RegisterAccountBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Email)
                    .addGroup(RegisterAccountBackgroundLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(EmailEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(RegisterAccountBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BirthDate)
                    .addComponent(datePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(RegisterNewUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GoBackToLoginArea)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(RegisterAccountBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(REgisterAccontPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(REgisterAccontPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(RegisterAccountBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseRegisterAccountFormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseRegisterAccountFormMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseRegisterAccountFormMouseClicked

    private void MinimizeRegisterAccountFormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeRegisterAccountFormMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_MinimizeRegisterAccountFormMouseClicked

    private void GoBackToLoginAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBackToLoginAreaActionPerformed
        // TODO add your handling code here:
        Login loginForm=new  Login();
        loginForm.setVisible(true);
        loginForm.pack();
        loginForm.setLocationRelativeTo(null);
        loginForm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_GoBackToLoginAreaActionPerformed

    private void RegisterNewUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterNewUserMouseClicked
        String firstName=FirstNameEntry.getText();
        String lastName=LastNameEntry.getText();
        String username=UsernameEntry.getText();
        String emailAddress=EmailEntry.getText();
        String pass=String.valueOf(EnterPassword.getPassword());
        String retypePass=String.valueOf(EnterPasswordAgain.getPassword());
        
        SimpleDateFormat date= new SimpleDateFormat("DD-MM-YYYY");
        
        String DOB=date.format(datePicker1.getDate());
        
        //Interface PreparedStatement interface executes a precomplied SQL Statement
        PreparedStatement sqlStatement;
        String sqlQuery="INSERT INTO 'TreasureHuntUsers'('first_Name','last_Name','username','email','username_Password','birthday')VALUES(?,?,?,?,?,?)";
        
        try {
            sqlStatement = ConnectionOfDatabase.getConnection().prepareStatement(sqlQuery);
            sqlStatement.setString(1,firstName);
            sqlStatement.setString(2,lastName);
            sqlStatement.setString(3,username);
            sqlStatement.setString(4,emailAddress);
            sqlStatement.setString(5,pass);
            sqlStatement.setString(6,DOB);
            
           //executeUpdate method returns the number of rows affected by the executed query
           if (sqlStatement.executeUpdate()>0)
           {
               JOptionPane.showMessageDialog(null,"New User Added.");
           }
        } catch (SQLException ex) {
            Logger.getLogger(CreateAccount.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_RegisterNewUserMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BirthDate;
    private javax.swing.JLabel CloseRegisterAccountForm;
    private javax.swing.JLabel Email;
    private javax.swing.JTextField EmailEntry;
    private javax.swing.JPasswordField EnterPassword;
    private javax.swing.JPasswordField EnterPasswordAgain;
    private javax.swing.JLabel FirstName;
    private javax.swing.JTextField FirstNameEntry;
    private javax.swing.JButton GoBackToLoginArea;
    private javax.swing.JLabel LastName;
    private javax.swing.JTextField LastNameEntry;
    private javax.swing.JLabel MinimizeRegisterAccountForm;
    private javax.swing.JLabel Password;
    private javax.swing.JPanel REgisterAccontPanel;
    private javax.swing.JPanel RegisterAccountBackground;
    private javax.swing.JButton RegisterNewUser;
    private javax.swing.JLabel RetypePassword;
    private javax.swing.JLabel Username;
    private javax.swing.JTextField UsernameEntry;
    private com.github.lgooddatepicker.components.DatePicker datePicker1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
